profiles:
  default:
    tour: pga
    enable_ai: true
    enable_backfill: true
    backfill_years: [2024, 2025, 2026]
    output_dir: output

  quick:
    tour: pga
    enable_ai: false
    enable_backfill: false
    output_dir: output

  full:
    tour: pga
    enable_ai: true
    enable_backfill: true
    backfill_years: [2020, 2021, 2022, 2023, 2024, 2025, 2026]
    output_dir: output
