"""
Setup Wizard

Interactive first-run wizard that:
  1. Checks Python version & dependencies
  2. Collects API keys (DataGolf, OpenAI, The Odds API)
  3. Writes .env file
  4. Initializes the database
  5. Optionally runs an initial data backfill
  6. Validates everything works

Run: python setup_wizard.py
"""

import os
import sys
import subprocess


def _clear():
    os.system("cls" if os.name == "nt" else "clear")


def _banner():
    print()
    print("=" * 60)
    print("    GOLF MODEL — SETUP WIZARD")
    print("    Professional Golf Prediction Engine")
    print("=" * 60)
    print()


def _check_python():
    v = sys.version_info
    print(f"  Python version: {v.major}.{v.minor}.{v.micro}")
    if v.major < 3 or (v.major == 3 and v.minor < 10):
        print("  WARNING: Python 3.10+ recommended. You may encounter issues.")
        return False
    print("  Python version OK")
    return True


def _check_dependencies():
    """Check and install required packages."""
    required = [
        "requests", "fastapi", "uvicorn", "python-dotenv",
    ]
    optional = ["openai", "pyyaml"]
    missing = []

    for pkg in required:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"\n  Missing required packages: {', '.join(missing)}")
        answer = input("  Install them now? (y/n): ").strip().lower()
        if answer == "y":
            for pkg in missing:
                print(f"  Installing {pkg}...")
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install",
                    "--trusted-host", "pypi.org",
                    "--trusted-host", "files.pythonhosted.org",
                    pkg
                ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("  Dependencies installed.")
        else:
            print("  Please install dependencies manually: pip install " + " ".join(missing))
            return False

    # Check optional
    for pkg in optional:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            print(f"  Optional package '{pkg}' not installed (some features may be limited)")

    return True


def _collect_api_keys() -> dict:
    """Interactively collect API keys."""
    print("\n  API KEY CONFIGURATION")
    print("  " + "-" * 40)
    print()

    keys = {}

    # DataGolf (required)
    print("  1. DataGolf API Key (REQUIRED)")
    print("     Get yours at: https://datagolf.com/api-access")
    print("     Subscription: Scratch Plus ($50/month) recommended")
    dg_key = input("     Enter DataGolf API key: ").strip()
    if dg_key:
        keys["DATAGOLF_API_KEY"] = dg_key
    else:
        print("     WARNING: DataGolf key is required for core functionality!")

    print()

    # OpenAI (optional but recommended)
    print("  2. OpenAI API Key (recommended for AI features)")
    print("     Get yours at: https://platform.openai.com/api-keys")
    ai_key = input("     Enter OpenAI API key (or press Enter to skip): ").strip()
    if ai_key:
        keys["OPENAI_API_KEY"] = ai_key
        keys["AI_PROVIDER"] = "openai"
        keys["AI_MODEL"] = "gpt-4o"

    print()

    # The Odds API (optional)
    print("  3. The Odds API Key (optional, for additional odds sources)")
    print("     Get yours at: https://the-odds-api.com/")
    odds_key = input("     Enter Odds API key (or press Enter to skip): ").strip()
    if odds_key:
        keys["ODDS_API_KEY"] = odds_key

    print()

    # Preferred sportsbook
    print("  4. Preferred Sportsbook (for EV calculations)")
    books = ["bet365", "draftkings", "fanduel", "betmgm", "caesars", "pinnacle"]
    for i, b in enumerate(books, 1):
        print(f"     {i}. {b}")
    choice = input("     Choose (1-6, default=1): ").strip()
    try:
        idx = int(choice) - 1
        keys["PREFERRED_BOOK"] = books[idx]
    except (ValueError, IndexError):
        keys["PREFERRED_BOOK"] = "bet365"

    return keys


def _write_env(keys: dict):
    """Write .env file."""
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

    # Preserve existing keys not being overwritten
    existing = {}
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()

    merged = {**existing, **keys}

    with open(env_path, "w") as f:
        f.write("# Golf Model Configuration\n")
        f.write("# Generated by setup_wizard.py\n\n")
        for k, v in sorted(merged.items()):
            f.write(f"{k}={v}\n")

    print(f"\n  .env file written to: {env_path}")
    print(f"  {len(merged)} configuration values saved")


def _init_database():
    """Initialize the database."""
    print("\n  Initializing database...")
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    from src.db import init_db
    init_db()
    print("  Database initialized successfully.")


def _run_initial_backfill():
    """Optionally run an initial data backfill."""
    print("\n  INITIAL DATA BACKFILL")
    print("  " + "-" * 40)
    print("  This downloads historical data from DataGolf.")
    print("  Recommended for backtesting. Takes 5-15 minutes.")
    print()

    answer = input("  Run initial backfill? (y/n, default=n): ").strip().lower()
    if answer != "y":
        print("  Skipping backfill. You can run it later with:")
        print("    python start.py backfill")
        return

    years_input = input("  Years to backfill (e.g., 2024,2025): ").strip()
    try:
        years = [int(y.strip()) for y in years_input.split(",")]
    except ValueError:
        years = [2024, 2025]

    from backtester.backfill import run_full_backfill
    run_full_backfill(tours=["pga"], years=years)


def _validate():
    """Run basic validation checks."""
    print("\n  VALIDATION")
    print("  " + "-" * 40)

    checks = []

    # Check .env
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if os.path.exists(env_path):
        checks.append(("  .env file exists", True))
    else:
        checks.append(("  .env file exists", False))

    # Check DB
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golf_model.db")
    if os.path.exists(db_path):
        checks.append(("  Database exists", True))
    else:
        checks.append(("  Database exists", False))

    # Check DataGolf key
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    dg_key = os.environ.get("DATAGOLF_API_KEY", "")
    checks.append(("  DataGolf API key set", bool(dg_key)))

    # Check imports
    try:
        from src.services.golf_model_service import GolfModelService
        checks.append(("  Core service imports", True))
    except Exception:
        checks.append(("  Core service imports", False))

    for label, ok in checks:
        status = "OK" if ok else "MISSING"
        print(f"  {label}: {status}")

    all_ok = all(ok for _, ok in checks)
    if all_ok:
        print("\n  All checks passed! You're ready to go.")
        print("\n  Quick start:")
        print("    python start.py analyze    — Run analysis for this week")
        print("    python start.py dashboard  — Open the web dashboard")
        print("    python start.py agent      — Start the research agent")
    else:
        print("\n  Some checks failed. Review the issues above.")

    return all_ok


def run_wizard():
    """Main wizard flow."""
    _clear()
    _banner()

    print("  Step 1: Checking Python...")
    _check_python()

    print("\n  Step 2: Checking dependencies...")
    _check_dependencies()

    print("\n  Step 3: API Key Configuration")
    keys = _collect_api_keys()

    print("\n  Step 4: Writing configuration...")
    _write_env(keys)

    print("\n  Step 5: Initializing database...")
    _init_database()

    print("\n  Step 6: Data backfill (optional)")
    _run_initial_backfill()

    print("\n  Step 7: Validating setup...")
    _validate()

    print()
    print("=" * 60)
    print("    SETUP COMPLETE!")
    print("=" * 60)
    print()


if __name__ == "__main__":
    run_wizard()
