#!/usr/bin/env python3
"""
Setup Wizard — Walk through first-time configuration step by step.

Run:  python setup.py
"""

import os
import sys
import subprocess
import shutil

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(PROJECT_DIR, ".env")
ENV_EXAMPLE = os.path.join(PROJECT_DIR, ".env.example")

# ── Helpers ────────────────────────────────────────────────────────

def _clear():
    os.system("cls" if os.name == "nt" else "clear")


def _banner(step: int, total: int, title: str):
    print()
    print(f"  {'='*54}")
    print(f"    GOLF MODEL SETUP  —  Step {step}/{total}: {title}")
    print(f"  {'='*54}")
    print()


def _ask(prompt: str, default: str = "", secret: bool = False, required: bool = False) -> str:
    """Prompt the user for input."""
    suffix = f" [{default}]" if default else ""
    if secret:
        suffix += " (paste key, won't be shown)"
    while True:
        try:
            val = input(f"  {prompt}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\n  Setup cancelled.")
            sys.exit(0)
        if not val and default:
            return default
        if not val and required:
            print("    This field is required. Please enter a value.\n")
            continue
        return val


def _yes_no(prompt: str, default: bool = True) -> bool:
    """Ask a yes/no question."""
    hint = "[Y/n]" if default else "[y/N]"
    val = _ask(f"{prompt} {hint}")
    if not val:
        return default
    return val.lower().startswith("y")


def _write_env(keys: dict):
    """Write or update the .env file."""
    existing = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()

    # Merge: new keys override existing
    existing.update(keys)

    with open(ENV_FILE, "w") as f:
        f.write("# Golf Betting Model — API Keys\n")
        f.write("# Generated by setup.py\n\n")
        for k, v in existing.items():
            if v:
                f.write(f"{k}={v}\n")
            else:
                f.write(f"# {k}=\n")


def _check_pip():
    """Check if pip packages are installed."""
    missing = []
    for pkg in ["pandas", "requests", "fastapi", "uvicorn", "openai"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    return missing


# ── Main ───────────────────────────────────────────────────────────

def main():
    _clear()
    print()
    print("  ╔══════════════════════════════════════════════════════╗")
    print("  ║                                                      ║")
    print("  ║          GOLF BETTING MODEL — SETUP WIZARD           ║")
    print("  ║                                                      ║")
    print("  ║   This will walk you through first-time setup.       ║")
    print("  ║   You'll need your API keys ready.                   ║")
    print("  ║   Press Ctrl+C at any time to cancel.                ║")
    print("  ║                                                      ║")
    print("  ╚══════════════════════════════════════════════════════╝")
    print()
    input("  Press Enter to begin...")

    total_steps = 6
    env_keys = {}

    # ── Step 1: Dependencies ──────────────────────────────────
    _clear()
    _banner(1, total_steps, "Install Dependencies")

    missing = _check_pip()
    if missing:
        print(f"  Missing packages: {', '.join(missing)}")
        print()
        if _yes_no("Install dependencies now? (pip install -r requirements.txt)"):
            print()
            print("  Installing...")
            result = subprocess.run(
                [sys.executable, "-m", "pip", "install", "-r",
                 os.path.join(PROJECT_DIR, "requirements.txt")],
                capture_output=False,
            )
            if result.returncode != 0:
                print()
                print("  WARNING: pip install had errors. You may need to:")
                print("    1. Fix SSL issues (try a different network)")
                print("    2. Run manually: pip install -r requirements.txt")
                print()
                input("  Press Enter to continue anyway...")
            else:
                print()
                print("  Dependencies installed successfully.")
                print()
                input("  Press Enter to continue...")
    else:
        print("  All dependencies already installed.")
        print()
        input("  Press Enter to continue...")

    # ── Step 2: Data Golf API Key ─────────────────────────────
    _clear()
    _banner(2, total_steps, "Data Golf API Key")

    print("  This is the most important key. It provides:")
    print("    - Historical round-level data (SG, stats, scores)")
    print("    - Pre-tournament predictions")
    print("    - Field updates (salaries, tee times)")
    print()
    print("  You need a Scratch Plus subscription ($30/mo or $270/yr).")
    print("  Get your key at: https://datagolf.com/api-access")
    print()

    dg_key = _ask("Data Golf API key", secret=True, required=True)
    env_keys["DATAGOLF_API_KEY"] = dg_key
    print()
    print("  Saved.")

    # ── Step 3: OpenAI API Key ────────────────────────────────
    _clear()
    _banner(3, total_steps, "OpenAI API Key (AI Brain)")

    print("  The AI brain uses OpenAI for:")
    print("    - Pre-tournament analysis (qualitative edge-finding)")
    print("    - Betting decisions (portfolio management)")
    print("    - Post-tournament review (learning + memory)")
    print()
    print("  Cost: ~$0.10/week. Very cheap.")
    print("  Get your key at: https://platform.openai.com/api-keys")
    print()
    print("  IMPORTANT: Never paste API keys in chat or commit them to git.")
    print("  This wizard stores them only in your local .env file.")
    print()

    openai_key = _ask("OpenAI API key (press Enter to skip for now)")
    if openai_key:
        env_keys["OPENAI_API_KEY"] = openai_key
        env_keys["AI_BRAIN_PROVIDER"] = "openai"
        print("\n  Saved. AI brain will use OpenAI (GPT-4o).")
    else:
        print("\n  Skipped. You can add this later in .env.")
        print("  The model works without the AI brain — it just won't have")
        print("  the qualitative analysis and betting decision layer.")

    print()
    input("  Press Enter to continue...")

    # ── Step 4: Anthropic API Key ─────────────────────────────
    _clear()
    _banner(4, total_steps, "Anthropic API Key (Course Profiles)")

    print("  Used for extracting course data from Betsperts screenshots")
    print("  (Course Facts, Off the Tee, Approach tables, etc.)")
    print()
    print("  This is optional — only needed if you want to upload")
    print("  course profile screenshots.")
    print()
    print("  Get your key at: https://console.anthropic.com/settings/keys")
    print()

    anthropic_key = _ask("Anthropic API key (press Enter to skip)")
    if anthropic_key:
        env_keys["ANTHROPIC_API_KEY"] = anthropic_key
        print("\n  Saved.")
    else:
        print("\n  Skipped. Course profile screenshots won't be available.")

    print()
    input("  Press Enter to continue...")

    # ── Step 5: The Odds API Key ──────────────────────────────
    _clear()
    _banner(5, total_steps, "The Odds API Key (Market Odds)")

    print("  Used for fetching live market odds from sportsbooks")
    print("  to calculate expected value (EV) on bets.")
    print()
    print("  This is optional — you can also enter odds manually.")
    print()
    print("  Get a free key at: https://the-odds-api.com")
    print()

    odds_key = _ask("The Odds API key (press Enter to skip)")
    if odds_key:
        env_keys["ODDS_API_KEY"] = odds_key
        print("\n  Saved.")
    else:
        print("\n  Skipped. You can enter odds manually or add this later.")

    print()
    input("  Press Enter to continue...")

    # ── Write .env ────────────────────────────────────────────
    _write_env(env_keys)

    # ── Step 6: Backfill Historical Data ──────────────────────
    _clear()
    _banner(6, total_steps, "Backfill Historical Data")

    print("  The model needs historical round data to compute player stats.")
    print("  This is a one-time operation that pulls 2-3 years of PGA Tour")
    print("  round-level data from Data Golf (~3 API calls).")
    print()
    print("  This takes about 30-60 seconds.")
    print()

    if _yes_no("Backfill PGA Tour data for 2024-2026 now?"):
        print()
        print("  Backfilling... (this may take a minute)")
        print()

        # Need to load .env first
        try:
            from dotenv import load_dotenv
            load_dotenv(ENV_FILE, override=True)
        except ImportError:
            # Manually set env vars
            for k, v in env_keys.items():
                os.environ[k] = v

        sys.path.insert(0, PROJECT_DIR)

        try:
            from src.datagolf import backfill_rounds
            summary = backfill_rounds(tours=["pga"], years=[2024, 2025, 2026])

            total_new = sum(
                v.get("rounds_new", 0) for v in summary.values()
                if isinstance(v, dict)
            )
            print()
            print(f"  Backfill complete! {total_new} new rounds stored.")
        except Exception as e:
            print(f"\n  Backfill error: {e}")
            print("  You can run this later:")
            print('    python analyze.py -t "Setup" -c "Setup" --backfill 2024 2025 2026')
    else:
        print()
        print("  Skipped. Run this later:")
        print('    python analyze.py -t "Setup" -c "Setup" --backfill 2024 2025 2026')

    # ── Done ──────────────────────────────────────────────────
    _clear()
    print()
    print("  ╔══════════════════════════════════════════════════════╗")
    print("  ║                                                      ║")
    print("  ║              SETUP COMPLETE!                         ║")
    print("  ║                                                      ║")
    print("  ╚══════════════════════════════════════════════════════╝")
    print()
    print("  Your .env file has been saved with your API keys.")
    print()
    print("  ── What's configured ─────────────────────────────────")
    for k, v in env_keys.items():
        status = "SET" if v else "skipped"
        # Mask keys for display
        if v and len(v) > 8:
            display = v[:4] + "..." + v[-4:]
        else:
            display = v or "(not set)"
        print(f"    {k}: {display}")
    print()
    print("  ── Next steps ────────────────────────────────────────")
    print()
    print("  Run your first analysis:")
    print('    python analyze.py -t "Genesis Invitational" -c "Riviera" --sync --ai')
    print()
    print("  Or start the web UI:")
    print("    python app.py")
    print("    Open http://localhost:8000")
    print()
    print("  Full docs: see README.md")
    print()


if __name__ == "__main__":
    main()
